In [3]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Dữ liệu giả định
data = np.array([[1], [2], [3], [4], [5]])

# Khởi tạo và fit scaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [7]:
import torch
import torch.nn as nn
import numpy as np

# Giả sử bạn có 5 mẫu, mỗi mẫu 10 thời điểm, mỗi thời điểm 3 biến
samples = 5
seq_length = 10
input_features = 3

# Tạo dữ kiện ngẫu nhiên
X = np.random.rand(samples, seq_length, input_features).astype(np.float32)
# Giả sử mỗi mẫu chỉ có 1 output (ví dụ PM2.5)
y = np.random.rand(samples, 1).astype(np.float32)

# Chuyển sang Tensor
X_tensor = torch.tensor(X)
y_tensor = torch.tensor(y)


In [8]:
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=1):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out, _ = self.lstm(x)  # (batch, seq_length, hidden_dim)
        out = out[:, -1, :]    # Lấy thời điểm cuối cùng
        return self.fc(out)   # (batch, 1)


# Khởi tạo mô hình
input_size = input_features  # = 3
hidden_size = 64
model = LSTMModel(input_size, hidden_size)


In [9]:
# Forward 1 batch dữ kiện
pred = model(X_tensor)

print("Predicted shape :", pred.shape)
print("Predicted values :", pred)


Predicted shape : torch.Size([5, 1])
Predicted values : tensor([[0.0961],
        [0.1111],
        [0.0977],
        [0.0929],
        [0.1000]], grad_fn=<AddmmBackward0>)


In [15]:
import torch
import torch.nn as nn

# Giả sử mỗi thời điểm bạn có 3 biến (input_features = 3)
# bạn muốn LSTM ghi nhớ những thông tin về thời gian
# sau khi xử lý, bạn chỉ dự đoán 1 giá trị (ví dụ: PM2.5)


# Đây chính là mô hình LSTM hoàn chỉnh
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=1):
        # Gọi hàm khởi động của cha (super) để khởi động nn.Module
        super().__init__()

        # Đây là LSTM - dòng này sẽ được gán vào biến của đối tượng
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)

        # Tiếp theo thêm 1 tầng fully connected để biến từ hidden sang output
        self.fc = nn.Linear(hidden_size, 1)  # 1 giá trị tại mỗi thời điểm cuối cùng

    # Hàm forward (đây chính là dòng xử lý chính khi bạn truyền dữ kiện vào mô hình)
    def forward(self, x):
        # x kích thước [batch, seq_length, input_features]

        # LSTM trả về:
        # - out: output tại mỗi thời điểm
        # - (h, c): hidden state & cell state (nhưng nếu bạn chưa dùng thì chỉ cần _)

        out, _ = self.lstm(x)  # (batch, seq_length, hidden_dim)

        # Chỉ quan tâm thời điểm cuối cùng
        out = out[:, -1, :]    # (batch, hidden_dim)

        # Sau khi có được dòng cuối cùng, đưa qua fully connected để ra output
        return self.fc(out)   # (batch, 1)


# Giả sử bạn có:
input_features = 3
hidden_dim = 64

# Tạo mô hình
model = LSTMModel(input_features, hidden_dim)
print("Model:")
print(model)


# Tạo dữ kiện mẫu
# 5 mẫu, mỗi mẫu 10 thời điểm, mỗi thời điểm 3 biến
batch = 5
seq_length = 10
X = torch.randn(batch, seq_length, input_features)

# Forward để kiểm chứng
output = model(X)
print("Output:")
print(output)
print("Output shape :", output.shape)


Model:
LSTMModel(
  (lstm): LSTM(3, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=1, bias=True)
)
Output:
tensor([[-0.0795],
        [-0.0122],
        [-0.0005],
        [-0.0574],
        [-0.0106]], grad_fn=<AddmmBackward0>)
Output shape : torch.Size([5, 1])


In [17]:
# Thay số tầng hoặc số nơron ẩn tại đây
input_features = 3
hidden_dim = 128
num_layers = 2

model = LSTMModel(input_features, hidden_dim, num_layers)
print(model)
batch = 5
seq_length = 10
X = torch.randn(batch, seq_length, input_features)

# Forward để kiểm chứng
output = model(X)
print("Output:")
print(output)
print("Output shape :", output.shape)


LSTMModel(
  (lstm): LSTM(3, 128, num_layers=2, batch_first=True)
  (fc): Linear(in_features=128, out_features=1, bias=True)
)
Output:
tensor([[0.0331],
        [0.0330],
        [0.0276],
        [0.0324],
        [0.0297]], grad_fn=<AddmmBackward0>)
Output shape : torch.Size([5, 1])


In [18]:
import torch

x = torch.tensor([1, 2, 3, 4])
print(x.shape)         # torch.Size([4])

# Chuyển thành tensor 2 chiều: 1 hàng, 4 cột
x_viewed = x.view(1, -1)
print(x_viewed)        # tensor([[1, 2, 3, 4]])
print(x_viewed.shape)  # torch.Size([1, 4])


torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


User Manual :train_loader, val_loader, test_loader


 train_loader (tập huấn luyện)<br>
📌 Dùng để huấn luyện mô hình: cập nhật trọng số bằng thuật toán tối ưu hóa (ví dụ SGD, Adam)
<br>
✅ Input: model, optimizer, loss_fn
<br>
✅ Output: mô hình học được từ dữ liệu
<br>
2. val_loader (tập kiểm tra/giám sát)<br>
📌 Dùng để đánh giá mô hình trong quá trình huấn luyện, nhưng không cập nhật trọng số.
<br>
✅ Giúp bạn kiểm tra: mô hình có học "thật" hay đang overfitting không?
<br>
✅ Được dùng sau mỗi epoch hoặc vài epoch
<br>
3. test_loader (tập kiểm tra cuối cùng)<br>
📌 Dùng để đánh giá mô hình cuối cùng sau khi huấn luyện xong.
<br>
✅ Kết quả ở test_loader cho biết mô hình tổng quát hóa tốt không
<br>
✅ Không được dùng để chọn mô hình (để tránh "leak")

